# Encoding Categorical Data

In [1]:
# Categorical Columns

In [2]:
# ordinal columns

In [2]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('customer.csv')
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [4]:
df['review'].value_counts()

review
Poor       18
Good       18
Average    14
Name: count, dtype: int64

In [5]:
df = df.iloc[:,2:]

In [6]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [8]:
from sklearn.preprocessing import OrdinalEncoder

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df[['review','education']],
                                                 df['purchased'],test_size=0.2,random_state=42)

In [10]:
x_train

     review education
12     Poor    School
4   Average        UG
37  Average        PG
8   Average        UG
3      Good        PG
6      Good    School
41     Good        PG
46     Poor        PG
47     Good        PG
15     Poor        UG
9      Good        UG
16     Poor        UG
24  Average        PG
34  Average    School
31     Poor    School
0   Average    School
44  Average        UG
27     Poor        PG
33     Good        PG
5   Average    School
29  Average        UG
11     Good        UG
36     Good        UG
1      Poor        UG
21  Average        PG
2      Good        PG
43     Poor        PG
35     Poor    School
23     Good    School
40     Good    School
10     Good        UG
22     Poor        PG
18     Good    School
49     Good        UG
20  Average    School
7      Poor    School
42     Good        PG
14     Poor        PG
28     Poor    School
38     Good    School

In [11]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [12]:
x_train = oe.transform(x_train)

In [13]:
x_train

array([[0., 0.],
       [1., 1.],
       [1., 2.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.]])

In [14]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [15]:
y_train

12     No
4      No
37    Yes
8      No
3      No
6      No
41    Yes
46     No
47    Yes
15     No
9     Yes
16    Yes
24    Yes
34     No
31    Yes
0      No
44     No
27     No
33    Yes
5     Yes
29    Yes
11    Yes
36    Yes
1      No
21     No
2      No
43     No
35    Yes
23     No
40     No
10    Yes
22    Yes
18     No
49     No
20    Yes
7     Yes
42    Yes
14    Yes
28     No
38     No
Name: purchased, dtype: object

In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
le = LabelEncoder()

In [18]:
le.fit(y_train)

LabelEncoder()

In [20]:
mod = le.transform(y_train)
mod2 = le.transform(y_test)

In [21]:
pd.DataFrame(mod,columns=['Purchased'])

    Purchased
0           0
1           0
2           1
3           0
4           0
5           0
6           1
7           0
8           1
9           0
10          1
11          1
12          1
13          0
14          1
15          0
16          0
17          0
18          1
19          1
20          1
21          1
22          1
23          0
24          0
25          0
26          0
27          1
28          0
29          0
30          1
31          1
32          0
33          0
34          1
35          1
36          1
37          1
38          0
39          0

# One Hot Encoding

One-Hot Encoding is a method used to convert categorical variables into a numerical format that machine learning algorithms can work with.

### Dummy Variable Trap

The dummy variable trap is a scenario in regression modeling (especially linear regression) where multicollinearity arises due to redundant one-hot encoded (dummy) variables.

When you one-hot encode a categorical variable with k categories, you get k binary columns. However, one of those columns is always predictable from the others (i.e., it's linearly dependent). his redundancy causes perfect multicollinearity, which can:
Confuse linear regression models Lead to unstable or non-unique coefficient estimates

In [22]:
df = pd.read_csv('cars.csv')

In [23]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [24]:
df = df[['km_driven','fuel','selling_price']]

In [25]:
df.head()

   km_driven    fuel  selling_price
0     145500  Diesel         450000
1     120000  Diesel         370000
2     140000  Petrol         158000
3     127000  Diesel         225000
4     120000  Petrol         130000

In [26]:
x_train,x_test,y_train,y_test = train_test_split(df.drop('selling_price',axis=1),
                                                 df['selling_price'],test_size=0.2,random_state=42)

In [27]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

# OneHotEncoding using pandas

In [26]:
pd.get_dummies(df,columns=['owner','fuel'],dtype=int)

,km_driven,selling_price,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol
0,145500,450000,1,0,0,0,0,0,1,0,0
1,120000,370000,0,0,1,0,0,0,1,0,0
2,140000,158000,0,0,0,0,1,0,0,0,1
3,127000,225000,1,0,0,0,0,0,1,0,0
4,120000,130000,1,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...
8123,110000,320000,1,0,0,0,0,0,0,0,1
8124,119000,135000,0,1,0,0,0,0,1,0,0
8125,120000,382000,1,0,0,0,0,0,1,0,0
8126,25000,290000,1,0,0,0,0,0,1,0,0
8127,25000,290000,1,0,0,0,0,0,1,0,0

# K-1 OneHotEncoding

In [28]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True,dtype=int)

,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,145500,450000,1,0,0,0,0,0,0
1,120000,370000,1,0,0,0,1,0,0
2,140000,158000,0,0,1,0,0,0,1
3,127000,225000,1,0,0,0,0,0,0
4,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...
8123,110000,320000,0,0,1,0,0,0,0
8124,119000,135000,1,0,0,1,0,0,0
8125,120000,382000,1,0,0,0,0,0,0
8126,25000,290000,1,0,0,0,0,0,0
8127,25000,290000,1,0,0,0,0,0,0

# Using Sklearn

In [29]:
from sklearn.preprocessing import OneHotEncoder

In [34]:
ohe = OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

In [35]:
x_train_ohe = ohe.fit_transform(x_train[['fuel']])

In [36]:
x_test_ohe = ohe.transform(x_test[['fuel']])

AttributeError: 'numpy.ndarray' object has no attribute 'values'

In [52]:
np.hstack((x_train[['km_driven']].values,x_train_ohe)).shape

(6502, 8)