### What is Pandas

Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
built on top of the Python programming language.

### Pandas Series

A Pandas Series is like a column in a table. It is a 1-D array holding data of any type.

### Importing Pandas

In [1]:
import numpy as np
import pandas as pd

### Series From List

In [2]:
# string
names = ["Amar","nehaal","Gopi","Sushmita"]
marks = [12,34,56,78]
pd.Series(names)

0        Amar
1      nehaal
2        Gopi
3    Sushmita
dtype: object

In [3]:
# integer

In [4]:
# custom indexing
names = ["Amar","nehaal","Gopi","Sushmita"]
marks = [12,34,56,78]

pd.Series(marks,index=["Amar","nehaal","Gopi","Sushmita"],name="Datamites Marks")

Amar        12
nehaal      34
Gopi        56
Sushmita    78
Name: Datamites Marks, dtype: int64

In [5]:
# Setting a name

### From Dictionary

In [6]:
d = {
    "Nasir" : 24,
    "Haroon" : 23,
    "Mehraj" : 26,
    "Dhuha" : 30,
    "Nikhil" : 32
}
d

{'Nasir': 24, 'Haroon': 23, 'Mehraj': 26, 'Dhuha': 30, 'Nikhil': 32}

In [7]:
ser = pd.Series(d)

In [8]:
ser

Nasir     24
Haroon    23
Mehraj    26
Dhuha     30
Nikhil    32
dtype: int64

### Series Attributes

In [9]:
e = pd.Series([1,2,3,4])
e

0    1
1    2
2    3
3    4
dtype: int64

In [10]:
e.size

4

In [11]:
ser

Nasir     24
Haroon    23
Mehraj    26
Dhuha     30
Nikhil    32
dtype: int64

In [12]:
# size
ser.size

5

In [13]:
# dtype
ser.dtype

dtype('int64')

In [14]:
# is_unique
ser.is_unique

True

In [15]:
# index
ser.index

Index(['Nasir', 'Haroon', 'Mehraj', 'Dhuha', 'Nikhil'], dtype='object')

In [16]:
# values
ser.values

array([24, 23, 26, 30, 32], dtype=int64)

### Series Methods

In [17]:
d1 = {
    "Nasir" : 24,
    "Haroon" : 23,
    "Mehraj" : 26,
    "Dhuha" : 30,
    "Nikhil" : 32,
    "Gopi" : 22,
    "Surya" : 10,
    "Yashwant" : 32,
    "Nasir" : 24,
    "Haroon" : 23,
    "Mehraj" : 26,
    "Dhuha" : 30,
    "Nikhil" : 32,
    "Gopi" : 22,
    "Surya" : 10,
    "Yashwant" : 32,
}
d1

{'Nasir': 24,
 'Haroon': 23,
 'Mehraj': 26,
 'Dhuha': 30,
 'Nikhil': 32,
 'Gopi': 22,
 'Surya': 10,
 'Yashwant': 32}

In [18]:
new = pd.Series({
    "Nasir" : 24,
    "Haroon" : 23,
    "Mehraj" : 26,
    "Dhuha" : 30,
    "Nikhil" : 32,
    "Gopi" : 22,
    "Surya" : 10,
    "Yashwant" : 32,
    "Nasir1" : 24,
    "Haroon2" : 23,
    "Mehraj3" : 26,
    "Dhuha4" : 30,
    "Nikhil5" : 32,
    "Gopi6" : 22,
    "Surya7" : 10,
    "Yashwant8" : 32,
})
new

Nasir        24
Haroon       23
Mehraj       26
Dhuha        30
Nikhil       32
Gopi         22
Surya        10
Yashwant     32
Nasir1       24
Haroon2      23
Mehraj3      26
Dhuha4       30
Nikhil5      32
Gopi6        22
Surya7       10
Yashwant8    32
dtype: int64

In [19]:
# head and tail
new.head(3)

new.tail()

Dhuha4       30
Nikhil5      32
Gopi6        22
Surya7       10
Yashwant8    32
dtype: int64

In [20]:
# sample
new.sample()

Nasir1    24
dtype: int64

In [21]:
# value_counts
new.value_counts()

32    4
24    2
23    2
26    2
30    2
22    2
10    2
Name: count, dtype: int64

In [22]:
# sort_values
new

Nasir        24
Haroon       23
Mehraj       26
Dhuha        30
Nikhil       32
Gopi         22
Surya        10
Yashwant     32
Nasir1       24
Haroon2      23
Mehraj3      26
Dhuha4       30
Nikhil5      32
Gopi6        22
Surya7       10
Yashwant8    32
dtype: int64

In [23]:
new.sort_values(ascending=False)

Nikhil       32
Yashwant     32
Nikhil5      32
Yashwant8    32
Dhuha        30
Dhuha4       30
Mehraj       26
Mehraj3      26
Nasir        24
Nasir1       24
Haroon       23
Haroon2      23
Gopi         22
Gopi6        22
Surya        10
Surya7       10
dtype: int64

In [24]:
# sort_index
new.sort_index()

Dhuha        30
Dhuha4       30
Gopi         22
Gopi6        22
Haroon       23
Haroon2      23
Mehraj       26
Mehraj3      26
Nasir        24
Nasir1       24
Nikhil       32
Nikhil5      32
Surya        10
Surya7       10
Yashwant     32
Yashwant8    32
dtype: int64

### Series Maths Methods

In [25]:
# count
new.count()

16

In [26]:
# sum/prod
new.sum()
new.prod()

492553463754915840

In [27]:
# mean -> median -> mode -> std -> var
print(new.mean())
print(new.median())
print(new.mode())
print(new.std())
print(new.var())

24.875
25.0
0    32
dtype: int64
6.955812916786458
48.38333333333333

In [28]:
# min/max
print(new.min())
print(new.max())

10
32

### Indexing and Slicing

In [29]:
new

Nasir        24
Haroon       23
Mehraj       26
Dhuha        30
Nikhil       32
Gopi         22
Surya        10
Yashwant     32
Nasir1       24
Haroon2      23
Mehraj3      26
Dhuha4       30
Nikhil5      32
Gopi6        22
Surya7       10
Yashwant8    32
dtype: int64

In [30]:
new[6]

C:\Users\Datamites\AppData\Local\Temp\ipykernel_7232\3376233358.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  new[6]

10

In [31]:
new['Surya']

10

In [32]:
new[5:13]

Gopi        22
Surya       10
Yashwant    32
Nasir1      24
Haroon2     23
Mehraj3     26
Dhuha4      30
Nikhil5     32
dtype: int64

In [33]:
new['Gopi':'Nikhil5']

Gopi        22
Surya       10
Yashwant    32
Nasir1      24
Haroon2     23
Mehraj3     26
Dhuha4      30
Nikhil5     32
dtype: int64

In [34]:
new[new > 25]

Mehraj       26
Dhuha        30
Nikhil       32
Yashwant     32
Mehraj3      26
Dhuha4       30
Nikhil5      32
Yashwant8    32
dtype: int64

### Editing Series

In [35]:
ser

Nasir     24
Haroon    23
Mehraj    26
Dhuha     30
Nikhil    32
dtype: int64

In [36]:
# using indexing
ser[1] = 28
ser

C:\Users\Datamites\AppData\Local\Temp\ipykernel_7232\692184484.py:2: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  ser[1] = 28

Nasir     24
Haroon    28
Mehraj    26
Dhuha     30
Nikhil    32
dtype: int64

In [37]:
# what if an index does not exist
ser['umer'] = 90
ser

Nasir     24
Haroon    28
Mehraj    26
Dhuha     30
Nikhil    32
umer      90
dtype: int64

### Series With Python Functionalities

In [38]:
# len/type/sorted/max/min
len(ser)
type(ser)
sorted(ser)
max(ser)
min(ser)

24

In [39]:
# size

In [40]:
ser['Radhika'] = np.nan
ser

Nasir      24.0
Haroon     28.0
Mehraj     26.0
Dhuha      30.0
Nikhil     32.0
umer       90.0
Radhika     NaN
dtype: float64

In [41]:
# isnull
ser.isnull().sum()

1

In [42]:
# dropna
ser.dropna()

Nasir     24.0
Haroon    28.0
Mehraj    26.0
Dhuha     30.0
Nikhil    32.0
umer      90.0
dtype: float64

In [43]:
ser

Nasir      24.0
Haroon     28.0
Mehraj     26.0
Dhuha      30.0
Nikhil     32.0
umer       90.0
Radhika     NaN
dtype: float64

In [44]:
# fillna
ser.fillna(4)

Nasir      24.0
Haroon     28.0
Mehraj     26.0
Dhuha      30.0
Nikhil     32.0
umer       90.0
Radhika     4.0
dtype: float64

In [45]:
ser.fillna(ser.mode()[0])

Nasir      24.0
Haroon     28.0
Mehraj     26.0
Dhuha      30.0
Nikhil     32.0
umer       90.0
Radhika    24.0
dtype: float64

In [46]:
ser.mode()[0]

24.0

In [47]:
ser.dtype

dtype('float64')

In [48]:
ser.astype('float32')

Nasir      24.0
Haroon     28.0
Mehraj     26.0
Dhuha      30.0
Nikhil     32.0
umer       90.0
Radhika     NaN
dtype: float32

### DataFrame

#### Creating DataFrame

In [49]:
# using dicts
dd = {
    "Student_name" : ["Nasir","Hussain","Nikhil","Surya","Duha"],
    "CGA" : [6.5,7.6,8.0,6.7,9.9],
    "LPA" : [10,20,12,14,18]
}
dd

{'Student_name': ['Nasir', 'Hussain', 'Nikhil', 'Surya', 'Duha'],
 'CGA': [6.5, 7.6, 8.0, 6.7, 9.9],
 'LPA': [10, 20, 12, 14, 18]}

In [50]:
new_df = pd.DataFrame(dd)

In [51]:
# using read_csv
df = pd.read_csv('train.csv')

In [52]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### DataFrame Attributes and Methods

In [53]:
# shape
df.shape

(891, 12)

In [54]:
# dtypes
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [55]:
# index
df.index

RangeIndex(start=0, stop=891, step=1)

In [56]:
# columns
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [57]:
# values
df.values

array([[1, 0, 3, ..., 7.25, nan, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, nan, 'S'],
       ...,
       [889, 0, 3, ..., 23.45, nan, 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, nan, 'Q']], dtype=object)

Methods

In [58]:
# head and tail
df.head(3)
df.tail(3)
df.sample(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
725,726,0,3,"Oreskovic, Mr. Luka",male,20.0,0,0,315094,8.6625,NaN,S
41,42,0,2,"Turpin, Mrs. William John Robert (Dorothy Ann ...",female,27.0,1,0,11668,21.0000,NaN,S
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S

In [59]:
# sample

In [60]:
# info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [61]:
# describe
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [62]:
df.describe(include='O')

                           Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [63]:
# isnull
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [64]:
# duplicated
df.duplicated().sum()

0

In [65]:
# rename (col={})
df.rename(columns={'Pclass':'PClass'},inplace=True)

In [66]:
df.head()

,PassengerId,Survived,PClass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Selecting cols from a DataFrame

In [67]:
# single column
df['Fare']

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

In [68]:
df.head(1)

,PassengerId,Survived,PClass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [69]:
# multiple columns
df[['PassengerId','PClass','Name','Cabin']]

,PassengerId,PClass,Name,Cabin
0,1,3,"Braund, Mr. Owen Harris",NaN
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",C85
2,3,3,"Heikkinen, Miss. Laina",NaN
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",C123
4,5,3,"Allen, Mr. William Henry",NaN
...,...,...,...,...
886,887,2,"Montvila, Rev. Juozas",NaN
887,888,1,"Graham, Miss. Margaret Edith",B42
888,889,3,"Johnston, Miss. Catherine Helen ""Carrie""",NaN
889,890,1,"Behr, Mr. Karl Howell",C148
890,891,3,"Dooley, Mr. Patrick",NaN

### Selecting rows from a DataFrame

- **iloc** - searches using index positions
- **loc** - searches using index labels

In [70]:
df.iloc[10:101]

,PassengerId,Survived,PClass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
97,98,1,1,"Greenfield, Mr. William Bertram",male,23.0,0,1,PC 17759,63.3583,D10 D12,C
98,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.0,0,1,231919,23.0000,NaN,S
99,100,0,2,"Kantor, Mr. Sinai",male,34.0,1,0,244367,26.0000,NaN,S
100,101,0,3,"Petranec, Miss. Matilda",female,28.0,0,0,349245,7.8958,NaN,S

In [71]:
new_df

  Student_name  CGA  LPA
0        Nasir  6.5   10
1      Hussain  7.6   20
2       Nikhil  8.0   12
3        Surya  6.7   14
4         Duha  9.9   18

In [72]:
df.head(1)

,PassengerId,Survived,PClass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [73]:
# value_counts
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [74]:
# sort_values
df['Age'].sort_values()

803    0.42
755    0.67
644    0.75
469    0.75
78     0.83
       ...
859     NaN
863     NaN
868     NaN
878     NaN
888     NaN
Name: Age, Length: 891, dtype: float64

In [75]:
# sort_index
df.sort_index()

,PassengerId,Survived,PClass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [76]:
# set_index
new_df.set_index('Student_name',inplace=True)

In [77]:
new_df

              CGA  LPA
Student_name
Nasir         6.5   10
Hussain       7.6   20
Nikhil        8.0   12
Surya         6.7   14
Duha          9.9   18

In [78]:
new_df.loc['Hussain':'Surya']

              CGA  LPA
Student_name
Hussain       7.6   20
Nikhil        8.0   12
Surya         6.7   14

In [79]:
# reset_index
new_df.reset_index(inplace=True)

In [80]:
new_df

  Student_name  CGA  LPA
0        Nasir  6.5   10
1      Hussain  7.6   20
2       Nikhil  8.0   12
3        Surya  6.7   14
4         Duha  9.9   18

In [83]:
# drop_duplicates
df.head(2)
df.drop_duplicates()

,PassengerId,Survived,PClass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### Group by

In [85]:
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [86]:
df.groupby('Embarked')['Age'].mean()

Embarked
C    30.814769
Q    28.089286
S    29.445397
Name: Age, dtype: float64

In [87]:
groups = df.groupby('Embarked')

In [88]:

groups['Age'].sum()

Embarked
C     4005.92
Q      786.50
S    16312.75
Name: Age, dtype: float64

In [98]:
# first/last/nth
groups.first()

,PassengerId,Survived,PClass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin
Embarked,,,,,,,,,,,
C,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85
Q,6,0,3,"Moran, Mr. James",male,2.0,0,0,330877,8.4583,C78
S,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,C123

In [99]:
groups.last()

,PassengerId,Survived,PClass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin
Embarked,,,,,,,,,,,
C,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148
Q,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,F38
S,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,19.0,1,2,W./C. 6607,23.45,B42

In [100]:
groups.size()

Embarked
C    168
Q     77
S    644
dtype: int64

In [103]:
groups.nth(7)

,PassengerId,Survived,PClass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C
47,48,1,3,"O'Driscoll, Miss. Bridget",female,NaN,0,0,14311,7.7500,NaN,Q

### Concatenation & Merging

In [92]:
new_df

  Student_name  CGA  LPA
0        Nasir  6.5   10
1      Hussain  7.6   20
2       Nikhil  8.0   12
3        Surya  6.7   14
4         Duha  9.9   18

In [93]:
d = {
    "Student_name" : ["Hi","hello","Reddy","vishwaj","Rimidi"],
    'CGA' : [2.3,4.3,5.6,7.8,2.3],
    'LPA' : [2,3,4,5,6]
}

In [94]:
new_df2 = pd.DataFrame(d)
new_df2

  Student_name  CGA  LPA
0           Hi  2.3    2
1        hello  4.3    3
2        Reddy  5.6    4
3      vishwaj  7.8    5
4       Rimidi  2.3    6

In [95]:
# pd.concat()
pd.concat((new_df,new_df2),axis=1)

  Student_name  CGA  LPA Student_name  CGA  LPA
0        Nasir  6.5   10           Hi  2.3    2
1      Hussain  7.6   20        hello  4.3    3
2       Nikhil  8.0   12        Reddy  5.6    4
3        Surya  6.7   14      vishwaj  7.8    5
4         Duha  9.9   18       Rimidi  2.3    6

In [96]:
# merge

In [97]:
# inner/outer/left/right